name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v2.3.4
    - uses: GuillaumeFalourd/assert-command-line-output@v2
      with:
        command_line: 
          g++ -std=c++11 -Wall delete_this.cpp -o delete_this
          ./delete_this
        contains: Hello World
        expected_result: PASSED
