name: Easy Test

on:
  workflow_call:
    inputs:
      file_paths:
        required: true
        type: string
      tests_folder:
        required: true
        type: string
      tests:
        required: true
        # type: array


jobs:
  test_it_all:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test: inputs.tests
        
    steps:
    - uses: actions/checkout@v3
#     - uses: actions/checkout@v2.3.4
    - name: compile
      run: gcc -std=c11 -Wall -o a.out $inputs.file_paths -lm

    - uses: GuillaumeFalourd/assert-command-line-output@v2
      with:
        command_line: ./a.out < $tests_folder/${{ matrix.test }}.in
        assert_file_path: $tests_folder/${{ matrix.test }}.out
        expected_result: PASSED
