name: Hello, Test

on:
  push:
    branches: [ main ]
    paths:
      - 'hello_test.cpp'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
#     - uses: actions/checkout@v2.3.4
    - name: compile
      run: g++ -std=c++11 -Wall hello_test.cpp -o hello_test
    - uses: GuillaumeFalourd/assert-command-line-output@v2
      with:
        command_line: ./hello_test
        contains: Hello World
        expected_result: PASSED
