name: Karatsuba Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'Karatsuba/karatsuba.c'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - input: ""
            output: ""
          - input: 1k
            output: 1k
          - input: 2k
            output: 2k
          - input: 5k
            output: 5k
          - input: -5k-3
            output: -5k-3
          - input: -5k-5
            output: -5k-5
          - input: 10k
            output: 10k
          - input: 20k
            output: 20k
          - input: 25k
            output: 25k
          - input: 30k
            output: 30k
        
    steps:
    - uses: actions/checkout@v3
#     - uses: actions/checkout@v2.3.4
    - name: compile
      run: gcc -std=c11 -Wall -o Karatsuba/karatsuba Karatsuba/karatsuba.c -lm

    - uses: GuillaumeFalourd/assert-command-line-output@v2
      with:
        command_line: ./Karatsuba/karatsuba ./Karatsuba/Inputs/input${{ matrix.input }}.txt
        assert_file_path: ./Karatsuba/Outputs/output${{ matrix.output }}.txt
        expected_result: PASSED
