name: Test Some Assignment
on:
  push:
    branches: [ main ]
    paths:
      - './SomeAssignment/'

jobs:
  Check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test_folder: [./SomeAssignment/Q01]
        test: [1, 2, 3, 4, 5]
        
    steps:
    - uses: actions/checkout@v3
#     - uses: actions/checkout@v2.3.4
    - name: compile
      run: gcc -std=c11 -Wall -o a.out ${{ matrix.test_folder }}/solution.c -lm

    - uses: GuillaumeFalourd/assert-command-line-output@v2
      with:
        command_line: ./a.out < ${{ matrix.test_folder }}/${{ matrix.test }}.in
        assert_file_path: ${{ matrix.test_folder }}/${{ matrix.test }}.out
        expected_result: PASSED
