name: Test Some Assignment
on:
  push:
    branches: [ main ]
#     paths:
#       - './SomeAssignment/'

jobs:
  test_it_all:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - test_folder: ./SomeAssignment/Q1/
            test: [1, 2, 3, 4, 5]
            file_paths: ./SomeAssignment/Q01/solution.c
        
    steps:
    - uses: actions/checkout@v3
#     - uses: actions/checkout@v2.3.4
    - name: compile
      run: gcc -std=c11 -Wall -o a.out ${{ matrix.files_paths }} -lm

    - uses: GuillaumeFalourd/assert-command-line-output@v2
      with:
        command_line: ./a.out < ${{ matrix.test_folder }}/${{ matrix.test }}.in
        assert_file_path: ${{ matrix.test_folder }}/${{ matrix.test }}.out
        expected_result: PASSED
